name: firefox-extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: pnpm/action-setup@v4
        with:
          version: 8
    - uses: actions/checkout@v4
    - name: Build extension
      run: cd extension && pnpm build --target=firefox-mv2
