name: firefox-extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

   - name: Install dependencies
       run: pnpm install
        
  - uses: actions/checkout@v4
  - name: Build extension
    run: cd extension && pnpm build --target=firefox-mv2
