name: firefox-extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
          cache: "pnpm"
  
  
      - name: build  
        run: git clone https://github.com/easychen/CookieCloud.git && cd CookieCloud/extension && npm install plasmo &&pnpm build --target=firefox-mv2
